Talend/tmdm-common

org.talend.mdm.base/pom.xml
pom.xml

DEVOPS-1729 Nexus migration: Update URLs [master]

---

org.talend.mdm.base/pom.xml
pom.xml

DEVOPS-1729 Nexus migration: Update URLs [maintenance/6.3]

---

org.talend.mdm.base/pom.xml
pom.xml

DEVOPS-1729 Nexus migration: Update URLs [maintenance/6.2]

---

org.talend.mdm.base/pom.xml
pom.xml

DEVOPS-1729 Nexus migration: Update URLs [maintenance/6.1]

---

main/plugins/org.talend.mdm.base/pom.xml

DEVOPS-1729 Nexus migration: Update URLs [patch/5.6.1]

---

main/plugins/org.talend.mdm.base/pom.xml

DEVOPS-1729 Nexus migration: Update URLs [patch/5.6.2]

---

org.talend.mdm.base/pom.xml
pom.xml

DEVOPS-1729 Nexus migration: Update URLs [patch/6.2.1]

---

org.talend.mdm.base/pom.xml
pom.xml

DEVOPS-1729 Nexus migration: Update URLs [patch/6.3.1]

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/webapp/XSystemObjects.java

Remove code related to license.

TMDM-11177 Remove license code

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/EncryptUtil.java

TMDM-11217: Remove DSC configurations

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/MDMConfiguration.java

Remove below code:
MDMConfiguration.isTdsEnabled()
Remove DSC Function

TMDM-11215: Remove DSC code from integrated matching

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/MDMConfiguration.java
org.talend.mdm.base/pom.xml

Access MDM Home page will redirect to MDM login page, authentication & authorization are base on MDM database.
- Add a new property `iam.enabled` in `mdm.conf` to control long mode
- If `iam.enabled=true`, using SSO login mode, including: IAM login page, authenticated by IAM but authorized by MDM
- if `iam.enabled=false`, work as before

TMDM-11200 Implement IAM UI Authentication Provider

---

org.talend.mdm.base/pom.xml

- update httpclient / fluent-hc version to 4.3.4, the same as datastewardship-client

TMDM-10673 Avoid code duplication

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/MDMConfiguration.java
org.talend.mdm.base/pom.xml

- Add dependency spring-security-oauth2

TMDM-11335 SSO:Error while bulk update

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/EncryptUtil.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/MDMConfiguration.java
org.talend.mdm.base/pom.xml

Encrypt oidc.client.secret property in mdm.conf file.

TMDM-11329 Encrypt oidc.client.secret when server start up.

---

org.talend.mdm.base/pom.xml

Issue 1 Relation button doesn't work
After we use WebSecurityConfigurerAdapter in sso,spring add 2 headers in response,they are 
X-Content-Type-Options: nosniff and X-XSS-Protection: 1; mode=block.IE 9(include above 9 version) need to specify Content-Type header in response.Content will be blocked by ie if miss Content-Type or Content-Type dismatched.
Please refer to
https://msdn.microsoft.com/query/dev12.query?appId=Dev12IDEF1&l=EN-US&k=k(VS.WebClient.Help.SEC7112)
https://blogs.msdn.microsoft.com/ie/2010/10/26/mime-handling-changes-in-internet-explorer/
Relation button will call dwr,we need load ItemsbrowserInterface.js from dwr,but dwr return text/plain content-type,it mismatch …

TMDM-11334 Multiple issues on WebUI after using SSO

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/webapp/XSystemObjects.java

Considered as an error and show error message in mdm problems view when creating Administrator type role lacking LicenseManager menu dependency.
Considered as a warning and show warning message in mdm problems view when creating Administrator type role lacking LicenseManager menu dependency.

TMDM-11332 Treat missing LicenseManager menu dependency as a warning.

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/ICoreConstants.java

TMDM-11432 Use of a constant as the System's roles prefix 

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/MDMConfiguration.java

TMDM-11316 Remove mdm.conf parameter to switch from legacy Authentication and Authorization mechanism

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/webapp/XSystemObjects.java

Existing 'LicenseManager' menu item added last commit.
Remove 'LicenseManager' menu item added last commit.

TMDM-11332 Remove 'LicenseManager' menu item.

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/ICoreConstants.java

https://jira.talendforge.org/browse/TMDM-11606
Define as a constant list of the MDM System roles to be reused.

TMDM-11606 [SSO] Users can log into MDM while they aren't allowed

---

org.talend.mdm.base/pom.xml

Add the audit log when login/logout

TMDM-11022 track/report login activity of the users on the MDM Web UI

---

org.talend.mdm.base/pom.xml

Add audit log for deploy/undeploy role
Add audit log for modify user's role

TMDM-11221 Capture audit event operations to MDM custom roles

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/ReferenceFieldMetadata.java

What is the current behavior? (You can also link to an open issue here)
Can't get correct filed information when records contains composite primary key field.
Add composite primary key field information when do search.

TMDM-11695 : Columns shifted in View when a composite primary key used as foreign key

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/ReferenceFieldMetadata.java

What is the current behavior? (You can also link to an open issue here)
Can't get correct filed information when records contains composite primary key field.
Add composite primary key field information when do search.

TMDM-11695 : Columns shifted in View when a composite primary key used as foreign key (#70) (#72)

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-11702
**What is the current behavior?**
audit property names are not standard. We need them to be generic enough to exploit the audit logs and be able to make relevant searches.
standard the named:
MDM replace all itemXXX fields by itemxxx
in common fields we will have:
user: "user0"
operation: "create user"
resource: "user"

TMDM-11702 [Audit] Use of a generic property name for items impacted by an action

---

org.talend.mdm.base/pom.xml

[INFO] |  +- org.talend.iam:oidc-client:jar:1-20170609142940-gd31e78f:compile
[INFO] |  |  +- org.talend.iam.scim:scim-client:jar:1-20170609142940-gd31e78f:compile
[INFO] |  |  |  +- org.talend.iam.scim:scim-common:jar:1-20170609142940-gd31e78f:compile
[INFO] |  |  |  |  \- rocks.xmpp:precis:jar:0.1.0:compile
[INFO] |  |  |  \- org.springframework.boot:spring-boot-autoconfigure:jar:1.5.2.RELEASE:compile
[INFO] |  |  |     \- org.springframework.boot:spring-boot:jar:1.5.2.RELEASE:compile
[INFO] |  |  +- org.springframework.security.oauth:spring-security-oauth2:jar:2.0.13.RELEASE:compile
[INFO] |  |  |  +- org.springframework:spring-webmvc:jar:4.3.7.RELEASE:compile
[INFO] |  |  |  \- …

TMDM-11739 Update jackson-core-asl-1.9.13.jar and jackson-mapper-asl-1.9.13.jar to Talend version.

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/ICoreConstants.java

Add administration to system role list and the roles in list is managed by tac.

TMDM-11716 [DEV] Defer to TAC the responsibility to manage the administration role

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/ICoreConstants.java

TMDM-11716 [DEV] Defer to TAC the responsibility to manage the administration role (release/7.0.1EP)

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-11787
Remove codes that DSC still remains.

TMDM-11787 Remove codes that DSC still remains.

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/ICoreConstants.java

https://jira.talendforge.org/browse/TMDM-11584
- TAC updated technical name of Super_Admin

TMDM-11584 Defer to TAC the responsibility to manage the administration role

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/MDMConfiguration.java

https://jira.talendforge.org/browse/TMDM-11795
- Global Logout will be enabled all the time
- For standalone environment, HashMap Store Type will always be used
- For cluster environment, Hazelcast Store Type will always be be used (system.cluster=true)
- For cluster environment, Auto Increment should not be affected although it uses same Hazelcast instance with Global Logout

TMDM-11795 Global logout support

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/ReferenceFieldMetadata.java

https://jira.talendforge.org/browse/TPS-2311

TPS-2311 [6.2.2] Columns shifted in View when a composite primary key used as foreign key (TMDM-11695)

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/ICoreConstants.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/webapp/XSystemObjects.java

https://jira.talendforge.org/browse/TMDM-11801

TMDM-11801 Remove System_View role

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/compare/Compare.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/compare/HibernateStorageImpactAnalyzer.java

Jira: https://jira.talendforge.org/browse/TMDM-10613
On 6.4.1
Action | Impact Level | Result
------------ | ------------- | -------------
Add a new optiona simple element | Low | Column is added
Add a new optiona complex element | High | Table is recreated
Action | Impact Level | Result
------------ | ------------- | -------------
Add a new anonymous  optiona complex element | Low | Table is added
Add a new non-anonymous  optiona  complex element | Low | Table is added
Add a new non-anonymous  mandatory complex element in new new anonymous/non-anonymous  optiona complex element | Low | Table is added
Add a new anonymous  mandatory complex element in new new anonymous/non-anonymous …

TMDM-10613 [Impact Analysis] Adding optional complex field recreates table

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/MetadataRepository.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/xsd/XmlSchemaWalker.java

Jira: https://jira.talendforge.org/browse/TMDM-12039
When parse xsd file of data model,  it first parse element, next parse complext type, for below data model, before modify and after modify, the type name of "**bb-anonymous**"is different, "**X_ANONYMOUS0**" for before modified, but after modify, it changed to "**X_ANONYMOUS1**":
Entity                                                                 Entity
|__id (SimpleField) (1-1)                                              |__id (SimpleField) (1-1)
|__aa-non-anonymous (ComplexType) (0-1)                                   |__aa-non-anonymous (ComplexType) (0-1)
|__aa-sub (SimpleField) (1-1)              ======>                       |__aa-sub (SimpleField) …

TMDM-12039 [Impact Analysis] Adding same complex field impact the existing one

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/compare/HibernateStorageImpactAnalyzer.java

Jira: https://jira.talendforge.org/browse/TMDM-12038
for simpletype field of complex type. modified from mandatory to optional, the impact result is **high**
for simpletype field of complex type. modified from mandatory to optional, the impact result is **low**

TMDM-12038 [Impact Analysis] High change when move a simple field from mandatory to optional in an complex type

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/compare/HibernateStorageImpactAnalyzer.java

Jira: https://jira.talendforge.org/browse/TMDM-12044
Impact result is High when delete simple field(mandatory or optional) in complex type
1. impact result changed to Medium from High when delete simple field(mandatory or optional) in complex type
2. alter the liquibase alter SQL scripter when deployed.
- [] Yes

TMDM-12044 [Impact Analysis] High change when deleting a simple field in a complex type

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/compare/HibernateStorageImpactAnalyzer.java

Revert "TMDM-12044 [Impact Analysis] High change when deleting a simple field in a complex type"

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/annotation/DefaultValueRuleProcessor.java

Jira: https://jira.talendforge.org/browse/TMDM-12515
1. add default value if is wrapped signal quation mask.

TMDM-12515 Can't prepare DB if field's type is MULTI_LINGUAL or boolean and has default value

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/annotation/DefaultValueRuleProcessor.java

Jira: https://jira.talendforge.org/browse/TMDM-12515
1. add default value if is wrapped signal quation mask.

TMDM-12515 Can't prepare DB if field's type is MULTI_LINGUAL or boolean and has default value (#96)

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/ReferenceFieldMetadata.java

…ve/Add FK value by import function
1) fix code issue
duplicate parameter
fixed code issue

TMDM-12497 A Role with 'No Remove Access' or 'No Add Access' can Remove/Add FK value by import function

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/validation/CircularComplexTypeValidationRule.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/validation/ValidationFactory.java

There is issue for cyclic dependency complex type
Added new Validation Rule to disable the case

TMDM-12560 Global search failed for data model with Cyclic Dependency

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/compare/HibernateStorageImpactAnalyzer.java

Jira: https://jira.talendforge.org/browse/TMDM-12621
backport TMDM-12038 to maintenance/7.0

Backprot TMDM-12038 [Impact Analysis] High change when move a simple field from mandatory to optional in an complex type (#538)

---

main/plugins/org.talend.mdm.commmon/src/main/resources/org/talend/mdm/commmon/metadata/compare/i18n/messages.properties

Add `add_reusable_type` to generic properties.

TMDM-11873	MDM Web UI translation in Chinese

---

main/plugins/org.talend.mdm.commmon/src/main/resources/org/talend/mdm/commmon/metadata/compare/i18n/messages.properties

Rename and add missing key of add_reusable_type

TMDM-12302 Wrong i18n file

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/MDMXMLUtils.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/exception/XmlBeanDefinitionException.java

there is security issue to parse xml using third xml library
resolve above issue.

TMDM-12544 Security issue: XXE injection

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/compare/AddChange.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/compare/Change.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/compare/HibernateStorageImpactAnalyzer.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/compare/RemoveChange.java

Jira: https://jira.talendforge.org/browse/TMDM-11044
Renamed FK field, have two impact result:
1. remove old field -> **Medium**
_remove this column in DB, but if contains data, will **lost data**._
2. add new field -> **Low**
_add new fcolumn in DB_
Contains data:
1. remove old field -> **High**
_recreate table, drop all data._
2. add new field -> Low
No data:
1. remove old field -> **Mdeidu**
_remove this column in DB_
2. add new field -> **Low**
_add new fcolumn in DB_
If this PR contains a breaking change, please describe the …

TMDM-11044 [Impact Analysis] Adapt Low/Medium Impact to Foreign Key field

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/MDMXMLUtils.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/exception/XmlBeanDefinitionException.java

Security issue: XXE injection
Fixed above XXE injectin issue.

TPS-2743 [6.4.1] Security issue: XXE injection (TMDM-12544)

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-12771
Upgrade org.springframework.security
spring-security-core    upgrade 4.2.2.RELEASE to 4.2.4.RELEASE
Upgrade org.talend.iam
oidc-client    upgrade 2.0.0-20180208135958-ge454bea to 7.1.1-20181022164905-gcf4b978

TMDM-12771 [CVE] org.springframework.security:spring-security-core

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-12866
Upgrade org.apache.httpcomponents
httpclient   upgrade 4.3.4 to 4.3.6
fluent-hc    upgrade 4.3.4 to 4.3.6
httpmime   upgrade 4.3.4 to 4.3.6
httpcore     upgrade 4.3.2 to 4.3.3
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.3.6:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.3.3:compile
https://jira.talendforge.org/browse/TMDM-12868
Upgrade org.apache.activemq
activemq-client                      upgrade 5.14.5 to 5.15.6
activemq-pool                       upgrade 5.14.5 to 5.15.6
activemq-jms-pool                upgrade 5.14.5 to 5.15.6
activemq-kahadb-store         upgrade 5.14.5 to 5.15.6
activemq-broker                    upgrade 5.14.5 to …

TMDM-12866 [CVE] org.apache.httpcomponents:httpclient org.apache.activemq:activemq-client 

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-10011
The journal button of record detail toolbar will open 'Journal' function,we can see all 'journal' records in this function.
The journal button of record detail toolbar will open 'User Journal' function, The User Journal will be only for single record and the pagination for the record's journal. We only see the records in view we have permission. The view and key search condition cannot be blank.
If this PR contains a breaking change, please describe the impact and migration path for existing …

TMDM-10011 Restrict journal view with role

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-12908
**What is the current behavior?** 
MDM code is relying on Tomcat 8, servlet 3 specs
Upgrade servlet api version to leverage new API when using Tomcat9 as the container

TMDM-12908 Align servlet api to Tomcat 9

---

org.talend.mdm.base/pom.xml

TMDM-12908 Align javax servlet version with Tomcat 9

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/compare/Change.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/compare/HibernateStorageImpactAnalyzer.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/compare/ModifyChange.java

Jira: https://jira.talendforge.org/browse/TMDM-13276
1. If increase the length for one string field, or db2, if greater than 255, for Oracle, if greater than 4000,  will redeploy failure.
1. if increase the length for one string field, for db2, if greater than 255, for Oracle, if greater than 4000, will give high impact result, 

TMDM-13276 [Impact Analysis] ElementType change (length) not reflected in PostgreSQL database tables

---

org.talend.mdm.base/pom.xml

CXF's version is 3.1.12.
Upgrade all CXF jar from 3.1.12 to 3.2.9.

TMDM-13501 CLONE - Can't get value in a workflow form (java 11) 

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/MetadataUtils.java

JIRA: https://jira.talendforge.org/browse/TMDM-13348
The order is not correct for one data model
1. Check all field when drawing the dependency graph.
-- now it only checks the entity's field which it is an entity, but for the complexTypeMetadata field, it doesn't check.
-- so it needs to check the entity's all the field, whatever it is an anonymous/non-anonymous complexTypeMetadata field.
2. Need fully check the reference
-- if contains dependence field, now it doesn't check all the dependence, for example
for the entity A, have three entity: B, C, D, also reference A, it checked the A->B, it stopped entity C & D are skipped.
-- here, need to check all the reference
3. Correct the …

TMDM-13348 Fail to import records with zip file for model RTE

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/MetadataUtils.java

JIRA: https://jira.talendforge.org/browse/TMDM-13348
The order is not correct for one data model
1. Check all field when drawing the dependency graph.
-- now it only checks the entity's field which it is an entity, but for the complexTypeMetadata field, it doesn't check.
-- so it needs to check the entity's all the field, whatever it is an anonymous/non-anonymous complexTypeMetadata field.
2. Need fully check the reference
-- if contains dependence field, now it doesn't check all the dependence, for example
for the entity A, have three entity: B, C, D, also reference A, it checked the A->B, it stopped entity C & D are skipped.
-- here, need to check all the reference
3. Correct the …

TMDM-13348 Fail to import records with zip file for model RTE (#138)

---

org.talend.mdm.base/pom.xml

Version of `org.talend.utils` is `6.20`
Upgrade version of `org.talend.utils` to `7.2.1`

TMDM-13680 Upgrade org.talend:org.talend.utils:jar with latest stable version

---

main/plugins/org.talend.mdm.commmon/META-INF/MANIFEST.MF

https://jira.talendforge.org/browse/TUP-24170

Fix TUP-24170 Set crypto-utils as bundle to make the master compile with daikon 0.31.10-SNAPSHOT

---

org.talend.mdm.base/pom.xml
org.talend.mdm.common/pom.xml

https://jira.talendforge.org/browse/TMDM-13681
- Use daikon-audit-0.20.0
- Use daikon-tql-core-0.29.0
- Use daikon-audit-1.5.0
- Use daikon-tql-core-1.5.0
- Add license for antlr4-runtime-4.7.jar after upgrade daikon

TMDM-13681 Upgrade org.talend.daikon with the latest stable version

---

org.talend.mdm.base/pom.xml

commons-fileupload:commons-fileupload vulnerability found in org.talend.mdm.base/pom.xml file.
upload to the latest version

TMDM-14061 [CVE] commons-fileupload:commons-fileupload

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-14062
com.fasterxml.jackson.core:jackson-databind vulnerabilities found in org.talend.mdm.core/pom.xml on May 23 Remediation
Upgrade com.fasterxml.jackson.core:jackson-databind to version 2.9.10

TMDM-14062 [CVE] com.fasterxml.jackson.core:jackson-databind

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-14064
Old the third package org.apache.httpcomponents:httpclient been found,it's a vulnerabilities issue, and need to upgrade to the latest version.
upgrade the old version to the latest version.

TMDM-14064 [CVE] org.apache.httpcomponents:httpclient

---

org.talend.mdm.base/pom.xml

Upgrade org.springframework.security:spring-security-core to version 4.2.13

TMDM-14060 [CVE] org.springframework.security:spring-security-core

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/Crypt.java

https://jira.talendforge.org/browse/TUP-21518
No behavior changes, just rename AES

feat(TUP-21518) Remove CryptoHelper

---

org.talend.mdm.base/pom.xml

TMDM-13949 Remove CryptoHelper and uptake AES algorithms(server)

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/Category.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/ComplexTypeMetadata.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/ComplexTypeMetadataImpl.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/ContainedComplexTypeMetadata.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/MetadataRepository.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/SoftTypeRef.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/UnresolvedTypeMetadata.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/annotation/CategoryAnnotationProcessor.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/annotation/XmlSchemaAnnotationProcessorState.java

No API to parse category annotation.
link: https://jira.talendforge.org/browse/TMDM-14173
Add new API to parse annotation of category.

TMDM-14173  Tab Management - Parsing annotation of Category

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-14171
Upgrade to CXF 3.3.4 , also update related jars.
workitem

TMDM-14148 Upgrade to CXF 3.3.4 (MDM)

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/MDMConfiguration.java

https://jira.talendforge.org/browse/TPS-3639

TPS-3639 [7.1.1] tMDMRollback somtimes let transactions "opened" (TMDM-14289)

---

org.talend.mdm.base/pom.xml

Jira: https://jira.talendforge.org/browse/TMDM-14192
Junit  and powermock version are low.
change the Junit version from 4.8.2 to 4.13
change the powermock version from 1.4.12 to 1.7.4

TMDM-14192 AUTO_INCREMENT value for NOT Primary Key reset to 0 after MDM restart 

---

org.talend.mdm.base/pom.xml

Jira: https://jira.talendforge.org/browse/TMDM-14192
Junit  and powermock version are low.
change the Junit version from 4.8.2 to 4.13
change the powermock version from 1.4.12 to 1.7.4

TMDM-14192 Upgrade Test dependencies versions

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-14128?filter=-1
Change the version of org.talend.utils to ${project.version}

TMDM-14128 Update version of org.talend.utils to release version 7.3.1 before release

---

org.talend.mdm.base/pom.xml

TPS-3686 [7.1.1] AUTO_INCREMENT value for NOT Primary Key reset to 0 after MDM restart (TMDM-14192)

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-14128
What is the current behavior? (You should also link to an open issue here)
org.talend.utils version is 7.3.1-SNAPSHOT
Change the version of org.talend.utils to 7.3.1

TMDM-14128 Update version of org.talend.utils to release version 7.3.1

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/Crypt.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/EncryptUtil.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/MDMConfiguration.java

https://jira.talendforge.org/browse/TMDM-14491
- Read .properties with default encoding
- Encode, decode with default encoding
- Read .properties set encoding as UTF-8 explicitly
- Encode, decode with encoding UTF-8 explicitly

TMDM-14491 Update encoding to UTF-8 explicitly for reading mdm.conf and encrypt/decrypt

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/Crypt.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/EncryptUtil.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/MDMConfiguration.java

https://jira.talendforge.org/browse/TMDM-14491
- With Consts.UTF-8 studio build would get compile issue.
- Change to StardardCharsets.UTF-8 to resolve the compile issue of Studio build

TMDM-14491 Change from Consts.UTF-8 to StardardCharsets.UTF-8 to resolve compile issue of NB.

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-14599
Previous BouncyCastle version 1.5.1 has been deprecated.
Upgrade new BouncyCastle version to 1.65

TMDM-14599 [CVE] Update BouncyCastle to 1.65

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-14599
https://jira.talendforge.org/browse/TMDM-14620
https://jira.talendforge.org/browse/TMDM-14627
https://jira.talendforge.org/browse/TMDM-14628
There was several CVE issues found from previous version libraries.
This task is to update libraries to pick up the fix for CVE issues.

TMDM-14628 Update Commons Codec to 1.13+

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-14651
- Using version of 2.7.1 which has CVE risk
- Upgrade to 2.7.2

TMDM-14651 [CVE] - Update Xalan to 2.7.2

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-14649
- Using version of 3.2.1 which has CVE risk
- Upgrade to 3.2.2

TMDM-14649 [CVE] - Update Commons Collections to 3.2.2

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-14656
- Using version of 2.9.1 which has CVE risk
- Upgrade to 2.12.0

TMDM-14656 [CVE] - Update XercesImpl to 2.12.0

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-14653
- Using version of 1.6.1 which has CVE risk
- Upgrade to 1.9.4

TMDM-14653 - Update Commons BeanUtils to 1.9.4

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-14656
- Using version of 2.9.1 which has CVE risk
- Upgrade to 2.12.0

TMDM-14656 - Update XercesImpl to 2.12.0

---

org.talend.mdm.base/pom.xml

Revert "TMDM-14656 - Update XercesImpl to 2.12.0"

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-14657
What is the current behavior? (You should also link to an open issue here)
Upgrade spring-security-config/spring-security-web to 4.2.13

TMDM-14657 [CVE] - Update Spring Security to 4.2.13

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/MDMXMLUtils.java
org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-14669
- Using dom4j 1.6.1 which get CVE issue
- Upgrade to 2.1.3

TMDM-14669 [CVE] - Update Dom4J to 2.1.3

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/annotation/DefaultValueRuleProcessor.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/compare/HibernateStorageImpactAnalyzer.java

TPS-4167 [7.0.1] Deploy Data Model fails after Element removed : ORA-00904: "X_VERSION" : invalid identifier (TMDM-14709)

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-14692
Updating bsh:bsh:2.0b1 to org.apache-extras.beanshell:bsh:2.0b6

TMDM-14692 [CVE] Update Beanshell

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-14751
Failed to startup MDM server on Ubuntu16 + OpenJDK11.
It is able to startup MDM server on Ubuntu16 + OpenJDK11, and on other platforms.

TMDM-14751 Failed to start mdm on Ubuntu16 + Open JDK11

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/ComplexTypeMetadataImpl.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/SimpleTypeMetadata.java

https://jira.talendforge.org/browse/TMDM-14573
As to REST query `rest/data/DM/query with condition "as_of":{"date":"xxxxx"}` in high concurrent request, that will met some weird exception, like `Caused by: java.lang.UnsupportedOperationException: No support for field typed as 'String10', and An exception occurred while closing storage '03891822-3394-4cf7-9bd7-8f86e847fc1c'`, etc.
Tomcat process each request in a separate worker thread, batch processes will cause some concurrent issue, so we have to synchronize individual threads with other parts of your program. and synchronize the access to a shared resource among the multiple threads.
Added synchronized block of code to …

TMDM-14573 [6.2.1,7.3.1] random error : Impossible to save itemAGRO_MIR_CLIENT_DonnCom.22531No Support for type 'String3'

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/ComplexTypeMetadataImpl.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/SimpleTypeMetadata.java

https://jira.talendforge.org/browse/TMDM-14573
As to REST query `rest/data/DM/query with condition "as_of":{"date":"xxxxx"}` in high concurrent request, that will met some weird exception, like `Caused by: java.lang.UnsupportedOperationException: No support for field typed as 'String10', and An exception occurred while closing storage '03891822-3394-4cf7-9bd7-8f86e847fc1c'`, etc.
Tomcat process each request in a separate worker thread, batch processes will cause some concurrent issue, so we have to synchronize individual threads with other parts of your program. and synchronize the access to a shared resource among the multiple threads.
Added synchronized block of code to …

TMDM-14573 [6.2.1,7.3.1] random error : Impossible to save itemAGRO_MIR_CLIENT_DonnCom.22531No Support for type 'String3' 

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-14865
1. Old dialect has been deprecated in hibernate 5.
2. Need to refactor code 
1. Replace Old dialect with new one in hibernate 5.
2. Refactor code 

TMDM-14865 [DEV] Upgrade Hibernate Dialect of DB

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/MDMXMLUtils.java

https://jira.talendforge.org/browse/TMDM-14878
During a Hibernate Session, loading batch of objects and some of them are loaded as proxies due to lazy loading. our code used session#get() to look up objects belonging to a type hierarchy that was mapped using the "join" strategy. Unfortunately, sometimes the queries were returning proxies of the base type instead of instances of the expected concrete types. This prevented we from casting the results to the correct types. so we got some error as follows:
```
Caused by: com.amalto.core.save.MultiRecordsSaveException: Could not set value with class 'org.talend.mdm.storage.hibernate.X_InformationsIdentiteSociete@1d9f0c39' to field 'InformationsIdentite'.
... 91 more …
```

TMDM-14878 tMDMoutput + Extended Output => com.amalto.core.save.MultiRecordsSaveException: Could not set value with class

---

org.talend.mdm.base/pom.xml

Jackson with version 1.9.14-TALEND
Use version of 1.9.15-TALEND

MDM-14876 Update Jackson version from 1.9.14-TALEND to 1.9.15-TALEND

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-14927
The repository for dependency library saxon was invalid for a long time, DA Jenkins build failed to download required Jar files.
The required Jar files was uploaded to Talend nexus repository and accessible from Jenkins build. 

TMDM-14927 Remove invalid repository url for saxon jars in pom.xml files

---

org.talend.mdm.base/pom.xml

TMDM-14946 High Memory used by MDM Tomcat JVM when calling REST API PUT with "as of " (7.3.1)

---

org.talend.mdm.base/pom.xml

TMDM-14946 High Memory used by MDM Tomcat JVM when calling REST API PUT with "as of " (7.4)

---

org.talend.mdm.base/pom.xml

TMDM-14946 High Memory used by MDM Tomcat JVM when calling REST API PUT with "as of " (7.2)

---

org.talend.mdm.base/pom.xml

TMDM-14946 High Memory used by MDM Tomcat JVM when calling REST API PUT with "as of" (7.2.1)

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-15020
The upgrade H2 version from 1.4.187 to 1.4.200
The upgrade H2 version from 1.4.187 to 1.4.200

TMDM-15020 CVE - Update H2 to 1.4.198

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-15045
Remove org.apache.ant dependency and exclude it from org.talend.utils

TMDM-15045 Remove org.apache.ant dependency

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-15032
Upgrade Hibernate-core package to resolve CVE.
Upgrade Hibernate-core package to resolve CVE.

TMDM-15032 Update Hibernate to 5.4.24.Final or higher

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-15060
Update daikon version to support log4j2

TMDM-15060  ClassNotFoundException: org.apache.log4j.RollingFileAppender

---

org.talend.mdm.base/pom.xml

TMDM-15082 Vulnerability found in jackson-databind lib

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/webapp/XSystemObjects.java

TMDM-15107  Remove bonita from MDM UI

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/AliasedFieldMetadata.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/ComplexTypeMetadata.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/ComplexTypeMetadataImpl.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/CompoundFieldMetadata.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/ContainedComplexTypeMetadata.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/ContainedTypeFieldMetadata.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/EnumerationFieldMetadata.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/FieldMetadata.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/MetadataRepository.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/ReferenceFieldMetadata.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/SimpleTypeFieldMetadata.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/SoftFieldRef.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/SoftIdFieldRef.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/SoftTypeRef.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/UnresolvedFieldMetadata.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/UnresolvedTypeMetadata.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/annotation/UserAccessProcessor.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/annotation/XmlSchemaAnnotationProcessorState.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/validation/PermissionValidationRule.java

TMDM-15108  Remove related soap api, workflow api and workflow triggersWorkitem/7.4/tmdm 15108

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/ICoreConstants.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/PermissionConstants.java

TMDM-15109 Remove from role permission, login module and related test

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-15089
upgrade oidc-client version from 7.1.1 to 7.3.1, also including other related package
upgrade oidc-client version from 7.1.1 to 7.3.1, also including other related package

TMDM-15089 Vulnerability found in spring-boot lib

---

main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/AliasedFieldMetadata.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/ComplexTypeMetadata.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/ComplexTypeMetadataImpl.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/CompoundFieldMetadata.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/ContainedComplexTypeMetadata.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/ContainedTypeFieldMetadata.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/EnumerationFieldMetadata.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/FieldMetadata.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/MetadataRepository.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/ReferenceFieldMetadata.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/SimpleTypeFieldMetadata.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/SoftFieldRef.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/SoftIdFieldRef.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/SoftTypeRef.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/UnresolvedFieldMetadata.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/UnresolvedTypeMetadata.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/annotation/UserAccessProcessor.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/annotation/XmlSchemaAnnotationProcessorState.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/validation/PermissionValidationRule.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/ICoreConstants.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/PermissionConstants.java
main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/webapp/XSystemObjects.java

https://jira.talendforge.org/browse/TMDM-15093
Bonita removal

TMDM-15093 Remove bonita integration - Implementation and clean up including validation

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-15132
Using version of 1.6.1 which has CVE risk
Upgrade to 1.9.4

TMDM-15132 BeanUtils upgrade

---

org.talend.mdm.base/pom.xml

TMDM-15060 ClassNotFoundException: org.apache.log4j.RollingFileAppender

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-15189
Upgrade spring related package to new version to fix CVE issue
Upgrade spring related package to new version to fix CVE issue

TMDM-15189 [CVE] - Update Spring on MDM

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TPS-5052

TPS-5052 [8.0.1] Talend MDM Log4j CVE-2021-44228/CVE-2021-45046 Security Issue (TMDM-15199)

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-15206#
Upgrade log4j2 to new version 2.17.1 to fix CVE issue
Upgrade log4j2 to new version 2.17.1 to fix CVE issue

TMDM-15206 MDM - Log4j2 CVE-2021-45105 DOS attack Fix - Version(2.17.1 update)

---

org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-15353
update org.restlet package
update org.restlet package

TMDM-15353 [CVE-2013-4221] - Update Restlet

---

main/plugins/org.talend.mdm.commmon/META-INF/MANIFEST.MF
org.talend.mdm.base/pom.xml

https://jira.talendforge.org/browse/TMDM-15479
update commons-configuration2 to version 2.9.0
update commons-configuration2 to version 2.9.0

fix(TMDM-15479): update commons-configuration2 to version 2.9.0
