Talend/tmdm-common

- org.talend.mdm.base/pom.xml
Will try do download datastewardship-client from TalendOpenSourceSnapshot, but it is not there.
Add repository of snapshots to pom.xml to make download the jar from it.
> TMDM-11327 Build org.talend.mdm.core.enterprise : datastewardship-client repository is wrong

- org.talend.mdm.base/pom.xml
https://jira.talendforge.org/browse/TMDM-12742
The class QueryParser is able to build an Expression from a JSON content (that is for most of the cases a Select clause, except for native queries).
But if one wants to use UserQueryBuilder to build a request that allows easy interaction with MDM REST API, the code is isolated in the MDM Server.
The user query construction is isolated into a new module org.talend.mdm.query to allow it to be reused from an external perspective.
On this project, just add the new module Maven build.
If this …
> TMDM-12742 Isolation UserQuery into new module

- org.talend.mdm.base/pom.xml
https://jira.talendforge.org/browse/TMDM-12558
We have jsr311-api-1.0.jar and javax.ws.rs-api-2.0.1.jar in class path,there is a conflict in class 'javax.ws.rs.core.Response'.We can not call the right class in Linux environment.
In order to prevent packaging multiple jars for the same classes,we remove dependency of jsr311-api-1.0.jar,we don't have jsr311-api-1.0.jar in mdm server any more.
> TMDM-12558 JAX-RS libraries conflicting

- org.talend.mdm.base/pom.xml
https://jira.talendforge.org/browse/TMDM-12558
We have jsr311-api-1.0.jar and javax.ws.rs-api-2.0.1.jar in class path,there is a conflict in class 'javax.ws.rs.core.Response'.We can not call the right class in Linux environment.
In order to prevent packaging multiple jars for the same classes,we remove dependency of jsr311-api-1.0.jar,we don't have jsr311-api-1.0.jar in mdm server any more.
> TMDM-12558 JAX-RS libraries conflicting.

- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/ReferenceFieldMetadata.java
Jira: https://jira.talendforge.org/browse/TMDM-13202
1. The Reference field in Container, the value of  **isFKMainRender** is not correct.
1. Reference field in Container, copy from the first instantiation, set **isFKMainRender** value when copy.
> TMDM-13202 FK : render in main tab in MetadataRepository

- org.talend.mdm.base/pom.xml
https://jira.talendforge.org/browse/TMDM-12592
MDM server couldn't be deployed in JRE 11.
This is to support Java 11 runtime for MDM server, so that MDM can be compiled in JDK 8 and deployed in JRE 8 or JRE 11.
> TMDM-12592 Java 11 support

- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/MetadataRepository.java
- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/annotation/DefaultValueRuleProcessor.java
- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/annotation/XmlSchemaAnnotationProcessorState.java
- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/compare/HibernateStorageImpactAnalyzer.java
Jira: https://jira.talendforge.org/browse/TMDM-13214
1. in field's data map, only used "default.value.rule" stored the constant default value, such constant string, number, true/false.
2. doesn't store the default value rule which is a function expression defined in Studio.
1. Change the key "default.value.rule" to "default.value" to store constant default value.
2. add new key "default.value.rule" to store default value rule which defined in studio, 
3. the default value rule have no any validation, the returned value is the input value:
Index|Input|Default.value|Default.value.rule
---- | ---- | ---- | ---
1|"Our"|"Our"|"Our"
2|Our|Null|Our
3|true|Null|true
4|false|Null|false …
> TMDM-13214 Default value expression in MetaDataRepository

- org.talend.mdm.base/pom.xml
In order to support Java 11, we used the jaxws-ri stack to cope with the missing JRE11 packages, that bringing a lot of unneeded dependencies.
we used the Web Service by CXF library all the time, in addition, CXF is the implementation of JAX-WS, so we turn to use existing CXF instead of JAXWS-RI to avoid lots of unneeded dependencies.
> TMDM-13532 Java 11 support (Server) - rationalize dependencies

- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/MetadataExtensions.java
- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/MetadataRepository.java
- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/validation/PermissionValidationRule.java
- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/validation/ValidationFactory.java
- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/PermissionConstants.java
https://jira.talendforge.org/browse/TMDM-14106
When do data model validation , it may give tip that hashmap capacity is aimed to contains no more than 12 elements. that's THRESHOLD 12 is NOT a proper value for hashmap .
Collect the model validation markers to set CUSTOMED hashmap's THRESHOLD.
> TMDM-14106 Validation error using customer's datamodel

- org.talend.mdm.base/pom.xml
Backport
- TMDM-12908 Talend MDM timeout cannot be increased with IAM enabled
> TPS-3569 [7.1.1] Talend MDM timeout cannot be increased with IAM enabled (TMDM-12908)

- org.talend.mdm.base/pom.xml
woodstox-core-asl-4.4.1.jar has conflict with   woodstox-core-5.3.0.jar when calling REST API
more detail please refer: https://jira.talendforge.org/browse/TMDM-14229?focusedCommentId=722246&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-722246
link: https://jira.talendforge.org/browse/TMDM-14229
Update the pom.xml file try to remove the "woodstox-core-asl-4.4.1.jar" from the library
**Other …
> TMDM-14229  [Rest API] Error on import records in batch mode

- org.talend.mdm.base/pom.xml
https://jira.talendforge.org/browse/TMDM-14229
Useless setting of `woodstox-core-asl` still exist in pom.xml
- Remove useless pom.xml setting of `woodstox-core-asl`
- talendmdm.war still the same after change
- bonita connector still the same after change
> TMDM-14229 [Rest API] Error on import records in batch mode

- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/MDMConfiguration.java
https://jira.talendforge.org/browse/TMDM-14289
A job that fails (exception) and calls tMDMRollback sometimes let a transaction "opened" (not commited , not rollbacked). It was found that storage begin may not completed with storage commit or storage rollback in a request if there are many requests from a loop Studio Job.
Added request number limit, this will ensure that a request can complete the whole process of transaction.
If this PR contains a breaking change, please describe the impact and migration path for existing applications: …
> TMDM-14289 tMDMRollback somtimes let transactions "opened" 

- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/MDMConfiguration.java
This is a revert the previous commit.
https://jira.talendforge.org/browse/TMDM-14289
A job that fails (exception) and calls tMDMRollback sometimes let a transaction "opened" (not commited , not rollbacked). It was found that storage begin may not completed with storage commit or storage rollback in a request if there are many requests from a loop Studio Job.
Added thread sleep between each for the transaction in SaverSession, this will ensure that a request can complete the whole process of transaction.
If this PR contains a breaking …
> TMDM-14289 tMDMRollback somtimes let transactions "opened"

- org.talend.mdm.base/pom.xml
Jira: https://jira.talendforge.org/browse/TMDM-14192
Junit  and powermock version are low.
change the Junit version from 4.8.2 to 4.13
change the powermock version from 1.4.12 to 1.7.4
> TMDM-14192 AUTO_INCREMENT value for NOT Primary Key reset to 0 after MDM restart 

- org.talend.mdm.base/pom.xml
Reverts Talend/tmdm-common#168
org.talend.utils would be built after the MDM , so dependency wouldn't be found
> Revert "TMDM-14128 Update version of org.talend.utils to release version 7.3.1 before release"

- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/EncryptUtil.java
https://jira.talendforge.org/browse/TMDM-14469
Encoding not set in EncryptUtil 
Set Encoding UTF-8 in encryptUtil. When tds password contains special character, the password can be saved correctly in mdm.conf after encrypt.
> TMDM-14469 MDM connecting to TDS with user/password contains special characters

- org.talend.mdm.base/pom.xml
https://jira.talendforge.org/browse/TMDM-14628
The dependent library Commons Codec 1.11 had a medium level CVE reported by Veracode.
This task is to update Commons Codec to 1.13+ to pick up a fix for a medium level CVE reported by Veracode. 
> TMDM-14628 Update Commons Codec to 1.13+

- org.talend.mdm.base/pom.xml
https://jira.talendforge.org/browse/TMDM-14627
Hibernate validator in tmdm-common/org.talend.mdm.base/pom.xml was 5.3.4.Final to 6.0.18.Final (or higher), which had issue of CVE-2019-10219.
Hibernate validator in tmdm-common/org.talend.mdm.base/pom.xml was updated to 6.0.18.Final to pick up a fix for CVE-2019-10219.
> TMDM-14627 Update Hibernate Validator to 6.0.18.Final+

- org.talend.mdm.base/pom.xml
https://jira.talendforge.org/browse/TMDM-14660
- JSTL verison is 1.2 which gets CVE risk
- Upgrade to 1.2.5
- Only affect SE version, which not included in official NB now
> TMDM-14660 [CVE] - Update JSTL to Apache Taglibs

- org.talend.mdm.base/pom.xml
- org.talend.mdm.common/pom.xml
https://jira.talendforge.org/browse/TMDM-14650
Exclude jackson explicitly from dependency of `org.talend.utils` to pass source clear checking.
> TMDM-14650 [CVE] - Update Jackson to 2.10.1 (exclude jackson from org.talend.utils)

- org.talend.mdm.base/pom.xml
https://jira.talendforge.org/browse/TMDM-14588
Apache CXF version 3.3.4 in ./tmdm-common/org.talend.mdm.base/pom.xml has issue of CVE-2020-1954
Update Apache CXF to 3.3.6 in ./tmdm-common/org.talend.mdm.base/pom.xml
> TMDM-14588 Update CXF to 3.3.6 due to CVE-2020-1954

- org.talend.mdm.base/pom.xml
https://jira.talendforge.org/browse/TMDM-14663
- lucene-queryparser of version 4.10.3 gets XXE risk
- Fix XXE issue in https://github.com/Talend/lucene-solr/commit/b7b23579ff99763b164730b54f09477e32a55ece
- new version jar with version 4.10.3-TALEND uploaded to talend nexus
> TMDM-14663 [CVE] - Update Lucene QueryParser to 5.5.5 (4.10.3-TALEND)

- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/ComplexTypeMetadataImpl.java
- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/ConsoleDumpMetadataVisitor.java
- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/DefaultMetadataVisitor.java
- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/DefaultValidationHandler.java
- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/MetadataRepository.java
- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/MetadataUtils.java
- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/compare/Compare.java
- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/validation/CircularComplexTypeValidationRule.java
- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/validation/XSDAttributeValidationRule.java
- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/EncryptUtil.java
- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/MDMConfiguration.java
- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/MDMXMLUtils.java
- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/workbench/ZipToFile.java
- org.talend.mdm.base/pom.xml
- org.talend.mdm.common/pom.xml
https://jira.talendforge.org/browse/TMDM-14697
Veracode is reporting a high level CVE against Log4J 1.2.17 as defined in mdm-common/org.talend.mdm.common/pom.xml
Updated Log4j from 1.2.17 to 2.12.1, this version can also work with PowerMock/Junit.
And updated log4j.xml to log4j2 format, and changed log4j.properties to log4j2.xml for Junit.
> TMDM-14697 [CVE] - Update Log4J 1.x

- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/ComplexTypeMetadataImpl.java
- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/CompoundFieldMetadata.java
https://jira.talendforge.org/browse/TMDM-14659
Previous version didn't support composite key in Join of MDM query, details can be found from Dev Design in Jira:
https://jira.talendforge.org/browse/TMDM-14659?focusedCommentId=805994&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-805994
Added support for composite key in Join of MDM query.
> TMDM-14659 [REST API] Throw UnsupportedOperationException when the foreign key points to an entity with composite key

- org.talend.mdm.base/pom.xml
https://jira.talendforge.org/browse/TMDM-14740
Current version of org.talend.utils in tmdm-common is 7.3.1, which used Log4j 1 directly in the source code, as DA also used tmdm-common, so DA pom file have to import Log4j 1.
Updated to new version of org.talend.utils which used slf4j, in MDM server or DA, we don't need to add Log4j 1 library explicitly.
> TMDM-14740 Remove Log4j 1 in pom of DA proxy once TUP-27949 is done

- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/annotation/DefaultValueRuleProcessor.java
Cherry-pick from maintenance/6.5
TMDM-12515 Can't prepare DB if field's type is MULTI_LINGUAL or boolean and has default value 
> TMDM-12515 Can't prepare DB if field's type is MULTI_LINGUAL or boolean and has default value

- org.talend.mdm.base/pom.xml
https://jira.talendforge.org/browse/TMDM-14790
Veracode is flagging a problem with the postgres version defined in tmdm-common/org.talend.mdm.base/pom.xml.
Removed Postgres in pom.xml.
> TMDM-14790 Updated postgres version

- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/metadata/Types.java
https://jira.talendforge.org/browse/TMDM-14831
Numeric type PK can't be sorted normally in Full-Text query
Numeric type PK will be indexed as string and sorted  as number
> TMDM-14831 [DEV] Fix sorting of numeric type fields

- org.talend.mdm.base/pom.xml
- org.talend.mdm.common/pom.xml
https://jira.talendforge.org/browse/TMDM-14853
Got exception from workflow process in Bonita server log file:
```
java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of org/bonitasoft/engine/classloader/BonitaClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of java/net/URLClassLoader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
```
Imported slf4j-log4j12-1.7.25.jar into mdm bonita connector pom file, …
> TMDM-14853 Failed to execute workflow task

- main/plugins/org.talend.mdm.commmon/src/main/java/org/talend/mdm/commmon/util/core/MDMXMLUtils.java
https://jira.talendforge.org/browse/TMDM-14878
During a Hibernate Session, loading batch of objects and some of them are loaded as proxies due to lazy loading. our code used session#get() to look up objects belonging to a type hierarchy that was mapped using the "join" strategy. Unfortunately, sometimes the queries were returning proxies of the base type instead of instances of the expected concrete types. This prevented we from casting the results to the correct types. so we got some error as follows:
```
Caused by: com.amalto.core.save.MultiRecordsSaveException: Could not set value with class 'org.talend.mdm.storage.hibernate.X_InformationsIdentiteSociete@1d9f0c39' to field 'InformationsIdentite'.
... 91 more …
```
> TMDM-14878 tMDMoutput + Extended Output => com.amalto.core.save.MultiRecordsSaveException: Could not set value with class

- org.talend.mdm.base/pom.xml
https://jira.talendforge.org/browse/TMDM-14946
High Memory used by MDM Tomcat JVM when calling REST API PUT with "as of "
The memory is OK when calling same REST API PUT with "as of"
> TMDM-14946 High Memory used by MDM Tomcat JVM when calling REST API PUT with "as of "

- org.talend.mdm.base/pom.xml
https://jira.talendforge.org/browse/TMDM-15119
net.sf.json-lib:json-lib is old, latest release was in 2009, for the safety, we consider using a different Jackson lib to replace it.
net.sf.json-lib:json-lib is old, latest release was in 2009, for the safety, we consider using a different Jackson lib to replace it.
> TMDM-15119 json-lib lib upgrade
